---
title: "Polynomial Simulation like in LRD paper"
author: "Adam C Sales & Ben B Hansen & Josh Wasserman"
date: "August 2022"
output:
  github_document:
    html_preview: false
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,error=FALSE,message=FALSE,warning=FALSE)
knitr::opts_knit$set(root.dir = '.')
```

General dependencies.
```{r}
library('knitr')
library('kableExtra')
source('displaySim.r')
devtools::load_all("../..")
```

The following gives the results in Table 4 of the paper, in addition
to the break-down of RMSE into bias and variance, and analogous
results for normally-distributed errors.

```{r}
load("totalPolySim.Rdata")
tab <- prntTab(totalPoly,5,full=TRUE)
#rownames(tab) <- rep(c('level','RMSE','bias','sd'),6)
colnames(tab) <- gsub('(flex|ols)\\.se.','deg=',colnames(tab))#c(rep(paste0('deg=',1:4),2),'')
# colnames(tab)[ncol(tab)] <- 'n/a' # this is for LLR column
kable(tab,format='html',caption='Full results for polynomial simulation',digits=2) %>%
  kable_styling() %>%
  column_spec(6,border_right=TRUE) %>%
  column_spec(11,border_right=TRUE) %>%
  # add_header_above(c(" " = 1, "flexida" = 5, "OLS" = 5, "Loc. Lin." = 1))%>%
  add_header_above(c(" " = 1, "flexida" = 5, "OLS" = 5))%>%
  #group_rows("$t_3$ Error",1,12)%>%group_rows("N(0,1) Error",13,24)%>%
  group_rows("linear",1,5) %>%
  group_rows('antiSym',6,10) %>%
  group_rows('sine',11,15) #%>% group_rows("linear",13,16)%>%group_rows('antiSym',17,20)%>%group_rows('oneSide',21,24)
```


Session information
```{r}
sessionInfo()
```
