on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Code-coverage

jobs:
  Code-coverage:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@master
        with:
          extra-packages: |
            remotes
            covr
            rcmdcheck
            CBPS
            haven
            DT

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Test coverage
        run: covr::zero_coverage(covr::package_coverage())
        shell: Rscript {0}
